# Form implementation generated from reading ui file 'c:\Users\DELL\Downloads\File Format Converter\Design\SplashScreen_File.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(680, 400)
        Form.setMinimumSize(QtCore.QSize(680, 400))
        Form.setMaximumSize(QtCore.QSize(680, 400))
        Form.setStyleSheet("background-color: rgb(40, 40, 70);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 50, 501, 61))
        self.label.setStyleSheet("color: rgb(254, 121, 199);\n"
"font: 28pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(230, 110, 201, 41))
        self.label_2.setStyleSheet("font-size: 8;")
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(20, 250, 631, 27))
        self.progressBar.setStyleSheet("\n"
"QProgressBar::chunk\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.523, stop:0 rgb(255, 32, 255), stop:1 rgb(161, 33, 225));\n"
"};\n"
"\n"
"background-color: rgb(98,114,150);\n"
"color: rgb(200, 200, 200);\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"font: 10pt bold \"Segeo UI\";")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(290, 290, 79, 28))
        self.label_3.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"text-align: center;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(280, 370, 101, 16))
        self.label_4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164)")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#fe2fab;\">File Format </span><span style=\" font-weight:600; color:#fe3585;\">Converter</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#6272a4;\">LOADING </span><span style=\" font-size:9pt; color:#6272a4;\">USER INTERFACE</span></p></body></html>"))
        self.progressBar.setFormat(_translate("Form", "%p%"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; color:#6272a4;\">loading...</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "Version 1.0.0"))
