# Form implementation generated from reading ui file 'c:\Users\DELL\Downloads\imap-Image-to-PDF-Converter-Application-For-Windows-master\SplashScreen.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 400)
        MainWindow.setMinimumSize(QtCore.QSize(680, 400))
        MainWindow.setMaximumSize(QtCore.QSize(680, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 680, 400))
        self.frame.setMinimumSize(QtCore.QSize(680, 400))
        self.frame.setMaximumSize(QtCore.QSize(680, 400))
        self.frame.setStyleSheet("background-color: rgb(40, 40, 70);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 70, 501, 61))
        self.label.setStyleSheet("color: rgb(254, 121, 199);\n"
"font: 28pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(240, 120, 201, 41))
        self.label_2.setStyleSheet("font-size: 8;")
        self.label_2.setObjectName("label_2")
        self.progress = QtWidgets.QProgressBar(self.frame)
        self.progress.setGeometry(QtCore.QRect(22, 262, 631, 27))
        self.progress.setStyleSheet("\n"
"QProgressBar::chunk\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511, x2:1, y2:0.523, stop:0 rgb(255, 32, 255, 255), stop:1 rgb(161, 33, 225,255));\n"
"};\n"
"\n"
"background-color: rgb(98,114,150);\n"
"color: rgb(200, 200, 200);\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"font: 10pt bold \"Segeo UI\";")
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(300, 300, 79, 28))
        self.label_3.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"text-align: center;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(280, 370, 101, 16))
        self.label_4.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164)")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#fe2fab;\">File Format </span><span style=\" font-weight:600; color:#fe3585;\">Converter</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#6272a4;\">LOADING </span><span style=\" font-size:9pt; color:#6272a4;\">USER INTERFACE</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#6272a4;\">loading...</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Version 1.0.0"))
